# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bindu = $mainMod, 36, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
# bind = $mainMod, O, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, E, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, X, togglesplit, # dwindle
bind = $mainMod, A, exec, hyprpicker -a -r
bind = $mainMod, F, fullscreen
